development:
  adapter: postgresql
  encoding: unicode
  database: helping_hands_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: helping_hands_test
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: helping_hands_production
  pool: 5
  timeout: 5000
